### ISSUE TITLE
D7 Issue - Add mapper to import product length, height, width

### ISSUE THREAD

**Issue by philsward** [backdrop-contrib/uc_feeds#3]
Would like to incorporate the patch from: https://www.drupal.org/project/uc_feeds/issues/3028121

This patch adds the length, height and width of a product to the mapper.

Like mentioned in the D7 issue, units need to be added however I recommend we get the dimensions committed and open a new issue for the units to be added later.

**Comment by stpaultim** [comment]
PR Merged.
